name: CI — NexaCloud API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('ressources/requirements.txt') }}

      - name: Installer les dépendances
        run: pip install -r ressources/requirements.txt

      - name: Lancer les tests
        run: pytest ressources/ -v

      - name: Tests avec couverture
        run: pytest ressources/ -v --cov=ressources --cov-report=term-missing

      - name: Générer le rapport HTML
        run: pytest ressources/ --cov=ressources --cov-report=html

      - name: Upload du rapport
        uses: actions/upload-artifact@v7
        with:
          name: rapport-couverture
          path: htmlcov/

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installer flake8
        run: pip install flake8

      - name: Lint avec flake8
        run: flake8 ressources/ --config ressources/.flake8