name: Deploy

on:
  workflow_dispatch:
    inputs:
      mon_input:
        description: "Choix de l'environnement de déploiement"
        required: true
        default: "deploy-staging"
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Déployer en ${{ inputs.environment }}
        run: |
          if [ "${{ inputs.environment }}" = "production" ]; then
            echo "🚀 Déploiement en PRODUCTION"
            echo "URL : https://nexacloud.example.com"
          else
            echo "✅ Déploiement en STAGING"
            echo "URL : https://staging.nexacloud.example.com"
          fi
