name: Secret Scanning

on:
  push:
    branches: ['*']
  workflow_dispatch:

jobs:
    secret-scanning :
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Scan secrets avec TruffleHog
          uses: trufflesecurity/trufflehog@main
          with:
            path: ./
            base: ${{ github.event.repository.default_branch }}
            head: HEAD
            extra_args: --only-verified
